// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa-HslopyHH8A6TixedApOAK--qGPIcos',
    appId: '1:158406708189:web:2e353fefb6efdaa0bd4434',
    messagingSenderId: '158406708189',
    projectId: 'inventory-app-27f47',
    authDomain: 'inventory-app-27f47.firebaseapp.com',
    storageBucket: 'inventory-app-27f47.firebasestorage.app',
    measurementId: 'G-6WWJ5ZKQHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV4AJUK29Pcaa_CPfeg6z-pFFmhbjURyo',
    appId: '1:158406708189:android:66a52f0ee2b0f879bd4434',
    messagingSenderId: '158406708189',
    projectId: 'inventory-app-27f47',
    storageBucket: 'inventory-app-27f47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTs-RCNevtZ6zt2uxBBGZAR9HO0mZ0jFI',
    appId: '1:158406708189:ios:6df409dff06789f0bd4434',
    messagingSenderId: '158406708189',
    projectId: 'inventory-app-27f47',
    storageBucket: 'inventory-app-27f47.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTs-RCNevtZ6zt2uxBBGZAR9HO0mZ0jFI',
    appId: '1:158406708189:ios:6df409dff06789f0bd4434',
    messagingSenderId: '158406708189',
    projectId: 'inventory-app-27f47',
    storageBucket: 'inventory-app-27f47.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa-HslopyHH8A6TixedApOAK--qGPIcos',
    appId: '1:158406708189:web:2f9596e1ecac5013bd4434',
    messagingSenderId: '158406708189',
    projectId: 'inventory-app-27f47',
    authDomain: 'inventory-app-27f47.firebaseapp.com',
    storageBucket: 'inventory-app-27f47.firebasestorage.app',
    measurementId: 'G-JK517BV14Z',
  );
}
